AWSTemplateFormatVersion: '2010-09-09'
Description: 'Stack for SNS topic with multiple SQS queues and Lambda consumers'

Resources:
  # SNS Topic
  NotificationTopic:
    Type: 'AWS::SNS::Topic'
    Properties:
      DisplayName: 'Customer segmentation Topic'
      TopicName: 'customer-segmentation-topic'

  # SQS Queues
  EmailProcessingQueue:
    Type: 'AWS::SQS::Queue'
    Properties:
      QueueName: 'email-processing-queue'
      VisibilityTimeout: 180

  FormProcessingQueue:
    Type: 'AWS::SQS::Queue'
    Properties:
      QueueName: 'form-processor-queue'
      VisibilityTimeout: 180

  ModelTrainingQueue:
    Type: 'AWS::SQS::Queue'
    Properties:
      QueueName: 'model-training-queue'
      VisibilityTimeout: 900

  # IAM Policy for SQS to allow SNS to send messages
  EmailProcessingQueuePolicy:
    Type: 'AWS::SQS::QueuePolicy'
    Properties:
      Queues:
        - !Ref EmailProcessingQueue
      PolicyDocument:
        Version: '2012-10-17'
        Id: 'Allow-SNS-Publish'
        Statement:
          - Effect: 'Allow'
            Principal: '*'
            Action: 'SQS:SendMessage'
            Resource: !GetAtt EmailProcessingQueue.Arn
            Condition:
              ArnEquals:
                aws:SourceArn: !Ref NotificationTopic

  FormProcessingQueuePolicy:
    Type: 'AWS::SQS::QueuePolicy'
    Properties:
      Queues:
        - !Ref FormProcessingQueue
      PolicyDocument:
        Version: '2012-10-17'
        Id: 'Allow-SNS-Publish'
        Statement:
          - Effect: 'Allow'
            Principal: '*'
            Action: 'SQS:SendMessage'
            Resource: !GetAtt FormProcessingQueue.Arn
            Condition:
              ArnEquals:
                aws:SourceArn: !Ref NotificationTopic

  ModelTrainingQueuePolicy:
    Type: 'AWS::SQS::QueuePolicy'
    Properties:
      Queues:
        - !Ref ModelTrainingQueue
      PolicyDocument:
        Version: '2012-10-17'
        Id: 'Allow-SNS-Publish'
        Statement:
          - Effect: 'Allow'
            Principal: '*'
            Action: 'SQS:SendMessage'
            Resource: !GetAtt ModelTrainingQueue.Arn

  # Lambda Functions
  EmailProcessorFunction:
    Type: 'AWS::Lambda::Function'
    Properties:
      FunctionName: 'email-processor-lambda'
      Timeout: 120
      MemorySize: 512
      PackageType: 'Image'
      Role: !GetAtt LambdaExecutionRole.Arn
      Code:
        ImageUri: '337909783829.dkr.ecr.us-east-1.amazonaws.com/aiml-dissertation-customer-segmentation-docker:latest'

  FormProcessorFunction:
    Type: 'AWS::Lambda::Function'
    Properties:
      FunctionName: 'form-processor-lambda'
      Timeout: 120
      MemorySize: 512
      PackageType: 'Image'
      Role: !GetAtt LambdaExecutionRole.Arn
      Code:
        ImageUri: '337909783829.dkr.ecr.us-east-1.amazonaws.com/aiml-dissertation-customer-segmentation-docker:latest'

  ModelTrainingFunction:
    Type: 'AWS::Lambda::Function'
    Properties:
      FunctionName: 'model-training-lambda'
      Timeout: 900
      MemorySize: 512
      PackageType: 'Image'
      Role: !GetAtt LambdaExecutionRole.Arn
      Code:
        ImageUri: '337909783829.dkr.ecr.us-east-1.amazonaws.com/aiml-dissertation-model-training-docker:latest'

  ModelDriftDetectionFunction:
    Type: 'AWS::Lambda::Function'
    Properties:
      FunctionName: 'model-drift-detection-lambda'
      Timeout: 300
      MemorySize: 512
      Role: !GetAtt LambdaExecutionRole.Arn
      Runtime: 'python3.9'
      Handler: 'app.lambda_handler'
      Code:
        S3Bucket: 'aiml-dissertation'
        S3Key: 'lambda/model-drift-detection-lambda.zip'

  ModelDriftDetectionSchedule:
    Type: 'AWS::Events::Rule'
    Properties:
      Name: 'ModelDriftDetectionWeeklyTrigger'
      ScheduleExpression: 'cron(0 1 ? * SUN *)'
      State: 'ENABLED'
      Targets:
        - Arn: !GetAtt ModelDriftDetectionFunction.Arn
          Id: 'ModelDriftDetectionTarget'

  ModelDriftDetectionPermission:
    Type: 'AWS::Lambda::Permission'
    Properties:
      Action: 'lambda:InvokeFunction'
      FunctionName: !Ref ModelDriftDetectionFunction
      Principal: 'events.amazonaws.com'
      SourceArn: !GetAtt ModelDriftDetectionSchedule.Arn

  # SNS Topic Subscription to SQS Queues
  EmailQueueSubscription:
    Type: 'AWS::SNS::Subscription'
    Properties:
      TopicArn: !Ref NotificationTopic
      Protocol: 'sqs'
      Endpoint: !GetAtt EmailProcessingQueue.Arn
      FilterPolicy:
        Source: ["email"]

  FormQueueSubscription:
    Type: 'AWS::SNS::Subscription'
    Properties:
      TopicArn: !Ref NotificationTopic
      Protocol: 'sqs'
      Endpoint: !GetAtt FormProcessingQueue.Arn
      FilterPolicy:
        Source: ["form"]

  # Lambda Permissions to SQS
  EmailLambdaSQSPermission:
    Type: 'AWS::Lambda::EventSourceMapping'
    Properties:
      BatchSize: 10
      EventSourceArn: !GetAtt EmailProcessingQueue.Arn
      FunctionName: !Ref EmailProcessorFunction
      Enabled: true

  FormLambdaSQSPermission:
    Type: 'AWS::Lambda::EventSourceMapping'
    Properties:
      BatchSize: 10
      EventSourceArn: !GetAtt FormProcessingQueue.Arn
      FunctionName: !Ref FormProcessorFunction
      Enabled: true

  ModelTrainingLambdaSQSPermission:
    Type: 'AWS::Lambda::EventSourceMapping'
    Properties:
      BatchSize: 10
      EventSourceArn: !GetAtt ModelTrainingQueue.Arn
      FunctionName: !Ref ModelTrainingFunction
      Enabled: true

  LambdaExecutionRole:
    Type: 'AWS::IAM::Role'
    Properties:
      RoleName: 'LambdaExecutionRole'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: 'Allow'
            Principal:
              Service: 
                - 'lambda.amazonaws.com'
            Action: 
              - 'sts:AssumeRole'
      Policies:
        - PolicyName: 'LambdaExecutionPolicy'
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: 'Allow'
                Action:
                  - 'logs:CreateLogGroup'
                  - 'logs:CreateLogStream'
                  - 'logs:PutLogEvents'
                Resource: 'arn:aws:logs:*:*:*'
              - Effect: 'Allow'
                Action:
                  - 'sqs:ReceiveMessage'
                  - 'sqs:DeleteMessage'
                  - 'sqs:GetQueueAttributes'
                Resource: '*'
              - Effect: 'Allow'
                Action:
                  - 's3:GetObject'
                Resource: 'arn:aws:s3:::aiml-dissertation/*'
